<a href="https://colab.research.google.com/github/Pimmiiiu/DW/blob/master/python1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hello PyThon
##Hello PyThon
###Hello Python
This is my first python

In [0]:
print("Hello World")

Hello World


#declare Variable
How to declare variable in python

In [0]:
score = 100
name ="Pukjira"
print(" Name is "+ name + " Score is " + str(score))

 Name is Pukjira Score is 100


In [0]:
a = 2
b = 3
c = a * b
print(c)

6


#List
How to use list python


In [9]:
mylist = []
mylist.append("Pukjira")
mylist.append(500)
mylist

['Pukjira', 500]

How to count Data in list

In [5]:
len(mylist)

2

#If Else 


In [14]:
if mylist[1] < 100 :
  name = mylist[0]
  score = mylist[1]
  print(name + " " + str(score))
elif mylist[1] >= 100 :
  print("Passssss")
elif mylist[1] > 500 :
  print("A")

Passssss


In [16]:
score = 5
if score < 2 :
  print("C")
elif score <= 4 :
  print("B")
elif score >= 5:
  print("A")

A


#For loop

In [24]:
summation = 0
for i in range(0,10) :
  print(str(i))
  summation = summation + 1
print("The summation result is " + str(summation))


0
1
2
3
4
5
6
7
8
9
The summation result is 10


In [26]:
summation = []
for i in range(1,10) :
  summation.append(i)
  
for i in summation :
  print(str(i))

1
2
3
4
5
6
7
8
9


In [33]:
summation = []
for i in range(0,10) :
  a = i * 2
  summation.append(a)
  print(str(a))

0
2
4
6
8
10
12
14
16
18


#Numpy

In [0]:
import numpy as np

In [41]:
l = [1,2,3,4]
np_array = np.array(l)
type(np_array)


numpy.ndarray

creat Matrix in array format

In [0]:
np_matrix = np.array([[1,2],[3,4],[5,6]])

In [43]:
np_matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

Check the dimension of this matrix

In [44]:
np.size(np_matrix,0)

3

In [45]:
np.size(np_matrix,1)

2

Check other matrix proerties

In [46]:
np_matrix.shape

(3, 2)

In [47]:
np_matrix.ndim

2

In [48]:
np_matrix.size

6

create Matrix with Mix Data Type

In [0]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])

In [51]:
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

Random matrix of size = (5,5)


In [52]:
np.random.rand(5,5)

array([[0.30152584, 0.18563855, 0.33803532, 0.39556245, 0.46383095],
       [0.93901183, 0.87518267, 0.35933851, 0.41559911, 0.09234557],
       [0.47698698, 0.33635849, 0.15404649, 0.41292343, 0.76737335],
       [0.6161004 , 0.80052245, 0.75863691, 0.55225536, 0.68218009],
       [0.67028248, 0.0188938 , 0.19192909, 0.91002375, 0.21024172]])

Random matrix of size = 3,3 having value between 0 to 4

In [55]:
np.random.randint(5,size = (3,3))

array([[3, 2, 1],
       [2, 2, 2],
       [4, 1, 2]])

In [58]:
np.random.randint(2,size = (10,5))

array([[1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1]])

In [59]:
np.zeros([0,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.empty([2])

array([7.74860419e-304, 7.74860419e-304])

#EX 1 

In [103]:
a = np.random.rand(10,5)
b = np.random.randint(2,size = (10))
a[:,4] = b
a

array([[0.50650412, 0.55814445, 0.37081948, 0.66074408, 1.        ],
       [0.05422235, 0.90687007, 0.99588008, 0.71874176, 1.        ],
       [0.9835244 , 0.08279498, 0.08328305, 0.79224835, 0.        ],
       [0.86979757, 0.77384752, 0.56856975, 0.34248259, 0.        ],
       [0.61483107, 0.76790444, 0.5289868 , 0.97373026, 0.        ],
       [0.2483852 , 0.08928755, 0.76653947, 0.55827518, 0.        ],
       [0.16746259, 0.13671579, 0.68680776, 0.03512438, 0.        ],
       [0.88959454, 0.55660042, 0.75151943, 0.96280163, 1.        ],
       [0.67393293, 0.14000505, 0.98631172, 0.92642796, 0.        ],
       [0.75023848, 0.14167033, 0.98456912, 0.7021096 , 1.        ]])

#EX 2

In [121]:
np_mat = np.random.rand(10,5)
np_mat

array([[0.32723319, 0.87954464, 0.79726936, 0.27156608, 0.77727412],
       [0.58809845, 0.76079966, 0.71473632, 0.76740488, 0.88013158],
       [0.86271822, 0.88893991, 0.65004494, 0.58077892, 0.16308633],
       [0.93413525, 0.61815425, 0.02352248, 0.51228244, 0.09712516],
       [0.06476505, 0.04735218, 0.23285031, 0.85909544, 0.79351475],
       [0.47423523, 0.73127133, 0.35854921, 0.99568261, 0.83019311],
       [0.98108297, 0.97965713, 0.83810659, 0.68918721, 0.06914085],
       [0.05000627, 0.48539428, 0.86220101, 0.08208341, 0.61490863],
       [0.89284008, 0.54064124, 0.42760135, 0.65718893, 0.6270378 ],
       [0.9880533 , 0.71752261, 0.5829916 , 0.94320951, 0.67552987]])

In [122]:
np_mat2 = np.random.randint(3,size = (10))
np_mat2

array([0, 1, 1, 0, 0, 1, 2, 2, 2, 2])

In [123]:
result = np.where(np_mat2 == 2 )
result

(array([6, 7, 8, 9]),)

In [124]:
np_mat[result,:]

array([[[0.98108297, 0.97965713, 0.83810659, 0.68918721, 0.06914085],
        [0.05000627, 0.48539428, 0.86220101, 0.08208341, 0.61490863],
        [0.89284008, 0.54064124, 0.42760135, 0.65718893, 0.6270378 ],
        [0.9880533 , 0.71752261, 0.5829916 , 0.94320951, 0.67552987]]])